### ISSUE TITLE
Two link arm example not working

### ISSUE THREAD

**Issue by nrkumar93** [PSOPT/psopt#29]
The two link arm example `twolinkarm.cxx` throws the following error

```
**** Run time error
**** To trace this error, set up your debugger to break at
**** function 'error_message', then do a backtrace.
**** A diagnostic message is given below:
**** ====> Index error in operator()(long) <====
```

The error occurs [here](https://github.com/PSOPT/psopt/blob/master/dmatrix/src/dmatrixv.cxx#L3939) when called from [here](https://github.com/PSOPT/psopt/blob/master/PSOPT/src/interpolation.cxx#L258). 

Thanks

**Comment by vmbecerra** [comment]
Please install the new release of PSOPT which has just been published. That error should no longer be there.
