### ISSUE TITLE
Could Function psopt() use const arguments?

### ISSUE THREAD

**Issue by schulz0r** [PSOPT/psopt#33]
Dear Victor,

I have a problem with the function `int psopt(Sol& solution, Prob& problem, Alg& algorithm)` which solves the trajectory optimization problem. Is it possible to mark the arguments for the `algorithm` and `problem` with `const`? I looked into the function and it did not seem to me that the optimizer changes anything about the two mentioned structs. Of course, it changes the solution for obvious reasons.
So, for my use case, I would like to change the function declaration to `int psopt(Sol& solution, const Prob& problem, const Alg& algorithm)`.
The reason is that the function where I use PSOPT is marked as const and does not let me use psopt() due to the reason stated above.

Greetings

Philipp

**Comment by schulz0r** [comment]
I cloned the code and tried to change that myself. I found that the function `save_jacobian_sparsity_pattern()` in IPOPT_interface.cxx sets an algorithm parameter, so the parameter `algorithm` cannot be `const`. Do you think there is a way to apply slight changes to the code design to make this work?
I will try to find a workaround, but this could actually help me not to ruin my code design.

**Comment by vmbecerra** [comment]
Phillip

Let me look into it and I will tell you if it can be done.

I'll do it this afternoon.

Best

Victor.

**Comment by schulz0r** [comment]
I managed to work around that issue and think it can be closed due to inactivity. It still would make sense to declare these parameters as constants, because the setup should not be changed by the solver function. However, this issue does not have priority.
