### ISSUE TITLE
psopt.org domain is offline

### ISSUE THREAD

**Issue by jankolf** [PSOPT/psopt#39]
Hi,
the [psopt.org](https://www.psopt.org) domain is offline and it is noted on the webpage, that the domain is for sale.
As the URL is still in the ReadMe, I wanted to notify you about this issue.

**Comment by vmbecerra** [comment]
Thank you. I have removed the reference to the website from the Readme file, while I try to recover the domain. This may be difficult and I may end up buying a slightly different domain.
