### ISSUE TITLE
Duplicate file

### ISSUE THREAD

**Issue by Sauermann** [PSOPT/psopt#4]
In the directory psopt/dmatrix/doc/latex/ there are two files in the repository:
DMatrix_Class_Reference.pdf
DMatrix_class_reference.pdf
which differ only in the case of the "C".

This causes problems on filesystems like Windows where filenames are caseinsensitive.
I want to suggest to remove one of them. However I can't be sure which one should be kept.

**Comment by vmbecerra** [comment]
Thanks. The (older) duplicate file has been removed.
