### ISSUE TITLE
additional design variables

### ISSUE THREAD

**Issue by dinesh286** [PSOPT/psopt#48]
i want to implement psopt for launch vehicle trajectory optimization.  the launch vehicle configuration is with strapons.  i have to optimize strapon ignition time and strapon separation time using psopt.  Also i dont want to add additional phases for this problem.  Is it possible to give additional design variables in addition to states and controls in PSOPT. if so kindly provide the detials.

**Comment by vmbecerra** [comment]
Hello, yes, it is possible to optimise additional design variables (apart from the states and controls). They are called 'static parameters' in PSOPT parlance. Just search for that phrase in the PSOPT user manual. If you look at the 'Low Trust Orbit Transfer' example on page 184, you will see how it is implemented. 

Best wishes,

Victor Becerra
